### ISSUE TITLE
Add transformation for injecting time-interval codes based on config specification

### ISSUE THREAD

**Issue by prenc** [mmcdermott/MEDS_transforms#120]
This is how I do it in [ETHOS](https://github.com/ipolharvard/ethos-paper):

Specification:
```yaml
time_intervals_spec:
  5m-15m:
    minutes: 5
  15m-1h:
    minutes: 15
  1h-2h:
    hours: 1
  2h-6h:
    hours: 2
#...
  1mt-3mt:
    weeks: 4
  3mt-6mt:
    weeks: 12
  =6mt:
    weeks: 24
```
The above is a list of breaks that specifies how to inject the time interval tokens. Everything below the first break (5 minutes) is omitted, i.e., no time interval will be added. The `5m-15m` interval goes into all gaps between events that are in the `[5min, 15min)` range, and so on, up to the last one `=6mt`, which is added as many times as it fits in the time gap (`time_gap // 24weeks`).

Rough Example:
![image](https://github.com/user-attachments/assets/07856131-cf52-4104-8ffe-21101ccd4791)
