### ISSUE TITLE
[Proposal] Stage configuration should be adjusted for brevity, to take advantage of dictionary ordering, and future proofing.

### ISSUE THREAD

**Issue by mmcdermott** [mmcdermott/MEDS_transforms#283]
Concrete proposal is that instead of:

```yaml
...
stage_configs:
  stage_B: {...}
  stage_A: {...}

stages:
  - stage_A
  - stage_B
  - stage_C

...
```

We should have
```yaml
...
stages:
  - stage_A: {...}
  - stage_B: {...}
  - stage_C

...
```

The reason to use a list in stages instead of just a plain object is that, in the future, we may want to have multiple stages combined to run without writing to/from disk. Plus, it is a functionally non-existent complexity cost while making it exceedingly clear that order matters.
