### ISSUE TITLE
Suggestion: Add warning/logging when rows are dropped due to time format parsing issues

### ISSUE THREAD

**Issue by kirilklein** [mmcdermott/MEDS_transforms#304]
I'm running `meds-transforms` using the following pipeline configuration:

```yaml
# config.yaml
defaults:
  - _extract
  - _self_

description: |-
  This pipeline extracts the preMEDS dataset in longitudinal, sparse form from an input dataset meeting
  select criteria and converts it to the flattened MEDS format...

event_conversion_config_fp: ${oc.env:EVENT_CONVERSION_CONFIG_FP}
input_dir: ${oc.env:PREMEDS_INPUT_DIR}
cohort_dir: ${oc.env:MEDS_OUTPUT_DIR}

etl_metadata:
  dataset_name: preMEDS
  dataset_version: 2.0

stage_configs:
  shard_events:
    infer_schema_length: 999999999
  split_and_shard_subjects:
    split_fracs:
      train: 0.8
      tuning: 0.1
      held_out: 0.1

stages:
  - shard_events
  - split_and_shard_subjects
  - convert_to_sharded_events
  - merge_to_MEDS_cohort
  - extract_code_metadata
  - finalize_MEDS_metadata
  - finalize_MEDS_data
```

With an `event_configs.yaml` like this:

```yaml
subject_id_col: subject_id

diagnosis:
  diagnosis:
    code:
      - col(code)
    time: col(timestamp)
    time_format: "%Y-%m-%d"
```

If the `time_format` is misspecified (e.g., doesn't match the actual format in the data), the pipeline applies a filtering step:

```
Filtering out rows with null times via col("timestamp").str.strptime(["raise"]).coalesce().is_not_null()
```

However, this step quietly drops rows that fail the time parsing, without any clear warning or indication of how many rows were affected. This can lead to entire tables being silently filtered out, which is especially problematic when working with many tables.

### Suggestion

It would be very helpful to:

1. Log a warning or info message indicating how many rows were dropped due to time parsing issues.
2. Optionally, log which table(s) had rows dropped or were completely removed.
3. (Optional) Consider auto-detecting time formats if none are specified or if parsing fails, though I understand this could add complexity.
