### ISSUE TITLE
Add transformation for split measurement

### ISSUE THREAD

**Issue by mmcdermott** [mmcdermott/MEDS_transforms#58]
This may leverage the match & revise syntax of #101

**Comment by mmcdermott** [comment]
The big question here @prenc is how to configure that you want a measurement split.

I default to something like the following:
```yaml
split_measurements:
  $field_name_1: 
    - $split_1_extractor_configuration
    - $split_2_extractor_configuration
  $field_name_2: # list of same length as $field_name_1
  # omitted fields are copied across all splits.
```

Thoughts?

**Comment by prenc** [comment]
No sure if I understand what is the split_1 split_2.

So what I exactly need right now is:
To convert this:
| code | text_value  |  numerical_value |
|---|---|---|
| BLOOD_PRESSURE | 120/80 | null |

Into this:
| code | text_value  |  numerical_value |
|---|---|---|
| BLOOD_PRESSURE | 120/80 | null |
| SBP | null | 120 |
| DBP | null | 80 |

It'd be the best if we could maintain the order, so we don't have to do it in a separate step. I think that it'd be the most often use case anyway. The question is whether we want the extracted values to go to `numerical_value` or `text_value` column. 

Are you proposing something like this given the example?
```yaml
split_measurements:
  BLOOD_PRESSURE: 
    - SBP: $split_1_extractor_configuration
    - DBP: $split_2_extractor_configuration
  $field_name_2:
```

**Comment by mmcdermott** [comment]
What is the motivation to retain the `BLOOD_PRESSURE` measurement? That can definitely be included, I'm just surprised.

I was picturing something like this (note I've added something like a match/revise syntax here, which is tracked in #101 but not yet finalized)

```yaml
split_measurements:
  - matching: {"code": "BLOOD_PRESSURE"}
    split:
      - code: "{code}//SYSTOLIC"
        text_value: "^([^/]+)/"
      - code: "{code}//DIASTOLIC"
        text_value: "/([^/]+)$"
```

| code | text_value  |  numeric_value |
|---|---|---|
| BLOOD_PRESSURE | 120/80 | null |
| HR | null | 78 |

Into this:
| code | text_value  |  numeric_value |
|---|---|---|
| SBP | 120 | null |
| DBP | 80 | null |
| HR | null | 78 |

**Comment by mmcdermott** [comment]
We might be able to use some of the stuff from here https://github.com/mmcdermott/MEDS_transforms/blob/main/src/MEDS_transforms/extract/parser.py to define the syntax for the extractor configuration blocks (with extending it for regex extraction or something).

Are there any other cases beyond BP where you need to split measurements currently?

**Comment by mmcdermott** [comment]
> Later I convert `BLOOD_PRESSURE//SYSTOLIC`, `BLOOD_PRESSURE//DIASTOLIC` into quantiles, but this is a separate step.

I see, so during final tokenization you want it to be something like `[CODE = BP], [CODE = VAL_QUANT_5], [CODE = VAL_QUANT_6], ...`. Well we can definitely configure it to retain the original measurement, or it can just be included in the split extractor configs, like below: 
```yaml
split_measurements:
  - matching: {"code": "BLOOD_PRESSURE"}
    split:
      - code: {"col": code}
        text_value: {"col": text_value}
      - code: "{code}//SYSTOLIC"
        text_value: {"extract": "^([^/]+)/", "from": "text_value"}
      - code: "{code}//DIASTOLIC"
        text_value: {"extract": "/([^/]+)$", "from": "text_value"}
```

**Comment by mmcdermott** [comment]
How does that (rough) syntax look to you?

**Comment by prenc** [comment]
> Are there any other cases beyond BP where you need to split measurements currently?
No, but the one with blood pressure repeat across different datasest.

>How does that (rough) syntax look to you?
It looks like everything what I need, and it's flexible. So I could instead of the key `text_value` use `numeric_value` to have it automatically converted to float?

**Comment by mmcdermott** [comment]
> > Are there any other cases beyond BP where you need to split measurements currently?
> 
> No, but the one with blood pressure repeat across different datasest.
> 
> > How does that (rough) syntax look to you?
> 
> It looks like everything what I need, and it's flexible. So I could instead of the key `text_value` use `numeric_value` to have it automatically converted to float?

We could add that, yes, I think. Only for `numeric_value`, given that that is a mandated typed MEDS field. Or, if we decide not to include that for whatever reason, it could be relegated to #57 to extract the numeric values, though that does seem a bit silly.

**Comment by mmcdermott** [comment]
This actually might be something we can capture just with the match & revise capability with a small addition. In particular, suppose I have a dataset with data:

| patient_id | time | code | text_value |
|------------|------|------|------------|
| 1          | 1/1  | HR   | null       |
| 1          | 1/1  | BP   | 120/80     |

And I have an `extract_values` transformation that takes a `categoric_regex` and a `numeric_regex`, applies them to the `text_value` field, and converts the result to either new code parts or new values, respectively. If I did the following

```yaml
stage_configs:
  extract_numeric_values:
    _match_and_revise:
      - _matcher: {code: BP}
        categoric_value: {lit: "SYSTOLIC"}
        numeric_value: {regex: "\d+/"}
      - _matcher: {code: BP}
        categoric_value: {lit: "DIASTOLIC"}
        numeric_value: {regex: "/\d+"}
```

I think that would do what we want, right @prenc?
